language: python
python:
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install pytest

jobs:
  include:
    - stage: test
      script: ./.travis/create-test-config.sh && pytest